using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TicketingMundialUCU.Data;

#nullable disable

namespace TicketingMundialUCU.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260620050000_UseNumericTokenQrPrimaryKey")]
public partial class UseNumericTokenQrPrimaryKey : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE tokens_qr
                DROP CONSTRAINT pk_tokens_qr CASCADE;

            ALTER TABLE tokens_qr
                DROP COLUMN id_token_qr;

            ALTER TABLE tokens_qr
                ADD COLUMN id_token_qr integer GENERATED BY DEFAULT AS IDENTITY;

            ALTER TABLE tokens_qr
                ADD CONSTRAINT pk_tokens_qr PRIMARY KEY (id_token_qr);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE tokens_qr
                DROP CONSTRAINT pk_tokens_qr;

            ALTER TABLE tokens_qr
                DROP COLUMN id_token_qr;

            ALTER TABLE tokens_qr
                ADD COLUMN id_token_qr uuid NOT NULL
                DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid);

            ALTER TABLE tokens_qr
                ADD CONSTRAINT pk_tokens_qr PRIMARY KEY (id_token_qr);
            """);
    }
}
